- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Privacy and Legal Statements"
  url: "http://www.psu.edu/legal-statements"
  title: "Privacy and Legal Statements"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
  
